program: train.py
# method can be random, grid, bayes
method: random
metric:
  goal: maximize
  name: val_accuracy
parameters:
  training.learning_rate:
    # log_uniform_values is a distribution that samples values from a log-uniform distribution.
    # basically, the odds of picking a value between 0.0001 and 0.001 is the same as the odds of picking a value between 0.001 and 0.01
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
  training.batch_size:
    # values is a distribution that samples values from a list of values.
    values: [8, 16, 32, 64]
  training.num_epochs:
    values: [5, 10, 15, 20]
  training.imgsz:
    values: [416, 512, 640, 768]
  hydra.job.chdir:
    value: False

# we specify the command explicitly for two reasons:
# 1. hydra wants the commands in no hyphen format. So wandb parameters can properly overwrite the base config
# 2. to use our precious uv (wandb otherwise defaults to regular python)
command:
  - uv
  - run
  - ${program}
  - ${args_no_hyphens}